# Generated by Django 6.0.4 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('in_stock', models.IntegerField()),
            ],
        ),
    ]
