# Generated by Django 6.0.4 on 2026-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.CharField(choices=[('classic', 'Классические часы'), ('smart', 'Смарт-часы')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='watch',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
